FROM node:latest
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY . .

RUN npm install
RUN npm install -g nx
RUN npm install pm2 -g

# Copy app source code

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

#Expose port and start application
EXPOSE 3000
RUN nx run api:build
CMD pm2 start ./dist/apps/api/main.js 