FROM node:12.20.1-alpine3.10
# Create app directory
WORKDIR /usr/src/app
# Install app dependencies
COPY . .

RUN npm install
RUN npm install -g nx
RUN npm install pm2 -g

# Copy app source code

ARG NODE_ENV=production

ENV NODE_ENV=${NODE_ENV}

#Expose port and start application
EXPOSE 4000
RUN npm run build:ssr
RUN npm run prerender
CMD pm2-runtime ./dist/site/server/main.js